# Generated by Django 3.0 on 2019-12-03 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ibx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ibx_name', models.CharField(max_length=250, verbose_name='IBX Name')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_fname', models.CharField(max_length=250, verbose_name='first name')),
                ('visitor_lname', models.CharField(max_length=250, verbose_name='last name')),
                ('visitor_uname', models.CharField(max_length=250, verbose_name='user name')),
                ('visitor_age', models.IntegerField(verbose_name='Age')),
                ('visitor_address', models.CharField(max_length=250, verbose_name='Address')),
                ('visitor_company', models.CharField(max_length=250, verbose_name='Company')),
            ],
        ),
        migrations.CreateModel(
            name='Cage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cage_name', models.CharField(max_length=250, verbose_name='Cage Name')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('ibx_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WorkVisits.Ibx')),
            ],
            options={
                'verbose_name_plural': 'cages',
            },
        ),
        migrations.CreateModel(
            name='Cabinets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet_name', models.CharField(max_length=250, verbose_name='Cabinet Name')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('cage_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WorkVisits.Cage')),
            ],
            options={
                'verbose_name_plural': 'cabinets',
            },
        ),
    ]
