# Generated by Django 3.0 on 2019-12-03 07:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WorkVisits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
