# Generated by Django 2.2.7 on 2019-12-04 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WorkVisits', '0002_visitors_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wv_start_date_time', models.DateTimeField()),
                ('wv_end_date_time', models.DateTimeField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('wv_cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkVisits.Cabinets')),
                ('wv_cage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkVisits.Cage')),
                ('wv_ibx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkVisits.Ibx')),
                ('wv_visitors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkVisits.Visitors')),
            ],
        ),
    ]
