# Generated by Django 2.2.7 on 2019-12-04 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WorkVisits', '0003_workvisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workvisit',
            name='wv_end_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='end datetime'),
        ),
        migrations.AlterField(
            model_name='workvisit',
            name='wv_start_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start datetime'),
        ),
    ]
