# Generated by Django 3.0 on 2019-12-05 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkVisits', '0004_auto_20191204_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workvisit',
            name='wv_end_date_time',
        ),
        migrations.RemoveField(
            model_name='workvisit',
            name='wv_start_date_time',
        ),
        migrations.RemoveField(
            model_name='workvisit',
            name='wv_visitors',
        ),
    ]
