# Generated by Django 3.0 on 2019-12-17 07:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WorkVisits', '0005_auto_20191205_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='gallery'),
            preserve_default=False,
        ),
    ]
